server:
  port: 9527

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){gray} %clr(%-6level) %clr(${PID:- }){magenta} %clr(---){gray} %clr([%15.15t]){blue} %clr(%logger{39}){cyan} %clr(:){green} %m%n%wEx"
